# Basic Information
title: Misan Omatsone
logo: "/images/profile.png?raw=true" # replace with your image file if needed
description: 
  p align="center">
  <a href="https://www.linkedin.com/in/misanomatsone/">LinkedIn</a> |
  <a href="https://github.com/willyrigz">GitHub</a>
  </p>
  
  <p align="justify">
  Data Analyst with 4+ years of commercial experience in data analytics, cloud technologies, and automation, holding a master’s degree in Data Science from Technological University Dublin.
  <br><br>
  Skilled in Python, SQL, R, Tableau, Power BI, and Advanced Statistical Modeling.
  <br><br>
  </p>

# Theme and Analytics
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # replace with your Google Analytics tracking ID if applicable

# Colors
colors:
  crimson: '#900C3F'
